# Generated by Django 4.2.29 on 2026-03-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplication_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='company_name',
            field=models.CharField(default='Company name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_posting_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_title',
            field=models.CharField(default='Job title', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
